### ISSUE TITLE
Error in line 30 Deployment Monitoring Example 

### ISSUE THREAD

**Issue by HammamWahab** [TorchDrift/TorchDrift#1]
Hi! 
In line 30 from the example in Monitor Model class (https://github.com/TorchDrift/TorchDrift/blob/master/notebooks/deployment_monitoring_example.ipynb)
`self.feature_rb[: bs - first_part] = self.output[first_part:]` 

I believe `self.output[: bs - first_part]` should only be `output[first_part:]` , is that correct? 

Thanks!

**Comment by t-vi** [comment]
Yes, thank you for reporting this!
