### ISSUE TITLE
Line 68 in ks.py, calculation of Emperical distribution Function  for Kolmogorov-Smirnov? 

### ISSUE THREAD

**Issue by HammamWahab** [TorchDrift/TorchDrift#11]
Hello TorchDrift team, 

First, I would like to truly thank you for this great package that is significantly supporting me in my research on drift detection. 
As I'm reading the paper "Numerically more stable computation of the p-values for the
two-sample Kolmogorov-Smirnov test" and reading the code in this repository, I have a question that I would like to ask .. 
- According to the paper, the empirical distribution function is calculated e.g for x as G(x) = = |{xi
: xi ≤ x}|/m 
- In the code (torchdrift.detector.ks.py) in line 68, the empirical distributions are calculated as `sign = (joint_sorted < n_x).to(dtype=torch.float) * (1 / (n_x) + 1 / (n_y)) - (
        1 / (n_y)`
Are these two points indicating the same thing? 

Thank you again

**Comment by t-vi** [comment]
This is a bit more detailed.
For signs: We sort the x_i and y_i. In each place in the sorted list we put 1/n_y if  the was from the x_i and -1/n_y.
Then in the next line, we treat the cumulative sum of the these values, i.e. in terms of the article F_m(x) - G_n(x), and take abs and max to compute D.

**Comment by HammamWahab** [comment]
Thank you very much for your response. 
If I understand correctly, then the negative sign in (-1/n_y) is nothing but a representation of -G_n(x). Would that be correct?
