### ISSUE TITLE
Dimensionality reduction for KernelMMDDriftDetector in the documentation?

### ISSUE THREAD

**Issue by kennysong** [TorchDrift/TorchDrift#3]
Hi, nice library! 

On the "[Comparing Drift Detectors](https://torchdrift.org/notebooks/comparing_drift_detectors.html)" page, what dimensionality reduction technique was used before the Kernel MMD?

Also, you tested an untrained autoencoder with the KS test, but did you also evaluate a trained autoencoder? I'm curious how it performs on ImageNet.

**Comment by t-vi** [comment]
Thank you. :bow:

We don't use an additional dimensionality reduction before the Kernel MMD but use the full extracted features. 

We didn't evaluate the trained autoencoder for any of the public demos. (Let's say we learnt not to use it from experience.) The conventional wisdom seems to be that autoencoders work reasonably well for more specific datasets (faces, cars, etc.) or smaller images (CIFAR) but I've not seen that many convincing autoencoders for all of ImageNet. As we're really only interested in the feature extraction part, one could think that using one of the recent self-supervised models might be more even natural these days... That said, if you have something that works well, we'd be very interested in adding that to the examples.

(The documentation is generated directly from the notebooks in the github repo / downloadable at the bottom, so you can easily experiment with these, too.)

**Comment by kennysong** [comment]
Got it! A self-supervised feature extractor would be an interesting experiment.

Does the univariate KS detector not work well directly on the features? I guess it's much higher dimensional than what the Failing Loudly paper tested?

(I would've tried myself, but I'm stuck on the setup cell since `/data/hymenoptera_data/test/` doesn't exist. I didn't read the code in detail so may be missing something obvious.)

I was also curious about the test sample size of `N=10`. To track shifted inputs at this "high fidelity", it seems more natural to do novelty detection on single points? And instead use drift detection on an entire day's worth of data, or something.

**Comment by t-vi** [comment]
So the KS detector does univariate KS on the marginals. In our experiments (at least the part I was involved in), it generally seemed to work worse or as good as MMD, so I personally adopted MMD to be my go-to metric (we do have some short-term plans to enhance some aspects of working with it).

Good catch with the missing test directory. I think I might have changed the datasource. I think you can just set the test dataset to `None`.

For the test sample size: This is clearly something where you need to balance sensitivity, specificity and the implications of test results. These vary greatly from application to application and involve the costs of false alarms and the harms of missed drifts.

**Comment by kennysong** [comment]
Got it, thanks for the discussion! 

(I did a test of KS without PCA, and it performs much better than the default example. Almost as good as MMD.)
